### ISSUE TITLE
Minor UI improvements

### ISSUE THREAD

**Issue by ghost** [nabijaczleweli/tackup#6]
Here are some minor UI improvements that I think this extension could benefit from:

1. Use seconds instead of milliseconds for the configuration interface.
2. Tweak the backup cleanup page layout, currently the "remove all" button is slightly confusing.
Maybe something like this could be more clear:

Select backup: `drop-down menu`
`remove selected`    `remove all older`    `remove all newer`
`remove all` of total 45 backups.

3. Use local time instead of UTC in the UI, but still store UTC in the actual backup, so if the time zone changes the backup doesn't get messed up. 

Thanks for all the great work so far, I hope you'd consider implementing some of them when you've got some spare time. I'd send you a PR but I can't write javascript :P

**Comment by nabijaczleweli** [comment]
The delay input will stay in milliseconds with the unit conv on the side, but otherwise, see [latest](https://github.com/nabijaczleweli/tackup/commit/df9c47fcc02d56ab94a18a8bef3c2cd3fde57307) [`master`](https://github.com/nabijaczleweli/tackup/commit/50875303e4edb9a5599c8d0e0589112480f887b3) for if the other two work for you?

**Comment by ghost** [comment]
👌 Cosmetic changes are all good, please check #5  for the new bug. Thanks.

**Comment by nabijaczleweli** [comment]
Released in [`v0.3.0`](https://github.com/nabijaczleweli/tackup/releases/tag/v0.3.0)
