### ISSUE TITLE
Toolbar button to open config page in new tab

### ISSUE THREAD

**Issue by grahamperrin** [nabijaczleweli/tackup#7]
Is an extension page possible? 

I see https://github.com/nabijaczleweli/tackup/issues/2#issuecomment-453840521

**Comment by nabijaczleweli** [comment]
The config page can be opened by its URL, e.g.: moz-extension://9dd4a6c6-2feb-45bf-adc1-b97aa1921b1d/assets/pages/config/index.html (if that link doesn't work, you should be able to substitute the Extension ID from about:debugging), but I'm not sure how to make it accessible otherwise. A toolbar button?

**Comment by grahamperrin** [comment]
Thanks. In my case: 

- moz-extension://233658f4-116e-458c-8379-3aaa3347e51c/assets/pages/config/index.html

A toolbar button is probably ideal.

**Comment by nabijaczleweli** [comment]
Can you check on the current `master` branch with the aforementioned commit?

**Comment by nabijaczleweli** [comment]
@grahamperrin *poke*

**Comment by nabijaczleweli** [comment]
@grahamperrin bump

**Comment by nabijaczleweli** [comment]
Released in [`v0.4.0`](https://github.com/nabijaczleweli/tackup/releases/tag/v0.4.0), but I'd still like your take on't

**Comment by grahamperrin** [comment]
Thanks! Apologies for the late response. 

I'd like a little more from the page, I'll raise a separate issue.
